export enum ROUTES {
  SWAGGER = '/api-docs',
  UPDATE_NAVER = '/update/naver',
  UPDATE_KAKAO = '/update/kakao',
  UPDATE_KAKAO_PAGE = '/update/kakao-page',
  HEALTH_CHECK = '/health-check',
  GET_WEBTOONS = '/webtoons',
  GET_KAKAO_PAGE_ABOUT = '/kakao-page/about',
  GET_EXTERNAL_WEBTOONS = '/external/webtoons',
  GET_EXTERNAL_WEBTOONS_SEARCH = '/external/search',
  GET_LEZHIN_ABOUT = '/lezhin/about',
  GET_TOOMICS_ABOUT = '/toomics/about',
  GET_RIDI_ABOUT = '/ridi/about',
  GET_TOPTOON_ABOUT = '/toptoon/about',
}
